#!/usr/bin/env bash
# Creates the file /var/run/myscript.pid containing its PID, displays "To infinity and beyond" indefinitely, displays "I hate the kill command" when receiving a SIGTERM signal, and displays "Y U no love me?!" when receiving a SIGINT signal


echo "$$" > /var/run/myscript.pid
trap "echo 'I hate the kill command'; rm /var/run/myscript.pid; exit" SIGTERM
trap "rm /var/run/myscript.pid; exit" SIGQUIT
trap "echo 'Y U no love me?!'" SIGINT
while true; 
do
      echo "To infinity and beyond"
      sleep 2
done
