#!/usr/bin/env bash
# the fizzbuzz problem for 1 - 100

num=1
while [ $num -ne 101 ]
do
	if (( num % 3 == 0 && num % 5 == 0 ))
	then
		echo "FizzBuzz"
	elif (( num % 3 == 0 ))
	then
		echo "Fizz"
	elif (( num % 5 == 0 ))
	then
		echo "Buzz"
	else
		echo $num
	fi
	(( num++ ))
done
