#!/usr/bin/env bash
# script to display 'Best School' 9 times with while loop
# and 'Hi' once - if the iterator is equal to 9

x=0
while [ $x -ne 10 ]
do
	if [ $x -eq 9 ]
	then
		echo "Hi"
	fi

	echo "Best School"
	x=$(( x + 1 ))
done

