#!/usr/bin/env bash
# script to display 'Best School' 8 times with while loop
# and 'bad luck' once - if the iterator is equal to 4
# and 'good luck' once - if the iterator is equal to 8

x=0
while [ $x -ne 10 ]
do
	if [ $x -eq 3 ]
	then
		echo "bad luck"
	elif [ $x -eq 7 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	x=$(( x + 1 ))
done

