#!/usr/bin/env bash
# script to display numbers from 1 to 20
# if iterator is 4, display 'bad luck form China'
# if the iterator is 9, 'bad luck from Japan'
# and if the iterator is 17 'bad luck from Italy'

x=1
while [ $x -ne 21 ]
do
	echo $x

	case $x in 
		"4") echo "bad luck from China";;
		"9") echo "bad luck from Japan";;
		"17") echo "bad luck from Italy";;
	esac
	x=$(( x + 1 ))
done

