#!/usr/bin/env bash
# script to display time in hours and minutes

hour=0
while [ $hour -ne 13 ]
do
	echo "Hour: $hour"
	minute=1
	while [ $minute -ne 60 ]
	do
		echo $minute
		(( minute++ ))
	done
	hour=$(( hour + 1 ))
done

