#!/usr/bin/env bash
# script to display the contents of the current directory in list form
# displays the name after the first dash, excluding hidden files

list=$(ls)

for file in $list;
do
	echo "$file" | cut -d '-' -f2
done
